2024-01-17 06:02:00,004:DEBUG:certbot._internal.main:certbot version: 2.8.0
2024-01-17 06:02:00,004:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-01-17 06:02:00,004:DEBUG:certbot._internal.main:Arguments: ['--webroot', '-w', '/var/www/certbot', '--email', 'tjfgkssk9472@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'tairot.online']
2024-01-17 06:02:00,005:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-01-17 06:02:00,222:DEBUG:certbot._internal.log:Root logging level set at 30
2024-01-17 06:02:00,230:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-01-17 06:02:00,231:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f41a1958a30>
Prep: True
2024-01-17 06:02:00,231:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f41a1958a30> and installer None
2024-01-17 06:02:00,232:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-01-17 06:02:00,306:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1519022676', new_authzr_uri=None, terms_of_service=None), 053f50e92556dc2ae6fb1958ad04b4cb, Meta(creation_dt=datetime.datetime(2024, 1, 16, 8, 39, 49, tzinfo=<UTC>), creation_host='1b0b13fa81e7', register_to_eff=None))>
2024-01-17 06:02:00,308:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-01-17 06:02:00,311:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-01-17 06:02:00,831:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-01-17 06:02:00,832:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 17 Jan 2024 06:02:00 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "sorK7JdsEas": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2024-01-17 06:02:00,835:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for tairot.online
2024-01-17 06:02:00,843:DEBUG:acme.client:Requesting fresh nonce
2024-01-17 06:02:00,844:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-01-17 06:02:01,022:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-01-17 06:02:01,025:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 17 Jan 2024 06:02:00 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4deRpJmQBceEGyw7Wxl9soOfVKKzJpfAU_hZgvJz_4KEs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-01-17 06:02:01,026:DEBUG:acme.client:Storing nonce: wFJtXv4deRpJmQBceEGyw7Wxl9soOfVKKzJpfAU_hZgvJz_4KEs
2024-01-17 06:02:01,027:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "tairot.online"\n    }\n  ]\n}'
2024-01-17 06:02:01,031:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZGVScEptUUJjZUVHeXc3V3hsOXNvT2ZWS0t6SnBmQVVfaFpndkp6XzRLRXMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "ooifl-UUbyS6o2RdKBtYSHjEVpIFzlyxDFsrFkoamNoUz1bslkvTf9AQlNFUkSzdHSjDH38Nae3tv8dH3MZhlTLXqMzr0-q8zPLN-1xkseFMHCLPN2U8kPNehrWKVIpkB3P0aK_sR9PkG4CufjcKQ5ga9tQ9uJWc8dvnhYCB4Bm_Q6wzI5_pDPxuNrPbgcnuzeSweuiIsjBWDD3it1OB8tWuCGylMRNj48g-Dr5Df8Gc_o61lUOXPatV9tuRAd1oQ1F83jLc-LuHM9JRuk5lSrLWvwelNA7wCxCA0oanvtquQ-6tMMcDm7Mk91nrC3xtPQ5UlBBqHzftQz3P3kk35g",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInRhaXJvdC5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-01-17 06:02:01,365:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 339
2024-01-17 06:02:01,366:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 17 Jan 2024 06:02:00 GMT
Content-Type: application/json
Content-Length: 339
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1519022676/237288711896
Replay-Nonce: wFJtXv4dKdjdKMSmYR1Fc6WewZvYNjZ41oR5FcHYo-4YaEZaW7w
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-01-24T06:02:00Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "tairot.online"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/305050750456"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1519022676/237288711896"
}
2024-01-17 06:02:01,367:DEBUG:acme.client:Storing nonce: wFJtXv4dKdjdKMSmYR1Fc6WewZvYNjZ41oR5FcHYo-4YaEZaW7w
2024-01-17 06:02:01,368:DEBUG:acme.client:JWS payload:
b''
2024-01-17 06:02:01,369:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/305050750456:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZEtkamRLTVNtWVIxRmM2V2V3WnZZTmpaNDFvUjVGY0hZby00WWFFWmFXN3ciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNTA1MDc1MDQ1NiJ9",
  "signature": "GT9ItOyDzJNQbaSq94YYKDGEnYPif3AFS4UIpbbm5W67S11aNUrJ7jt3lQ-z5iDakgMqHGcSx0X1tNGZwx07EIRn199WmhJL9tVot0Drfwv9vfUR5f9mIxVmnoAeacgiWjCUh5zbh5eAI3I4YH5mCTw05q7woF1mVNC83XDubA-eqqRFQhJT5OMgzuI9drBOT7vRZOhXW16w1JcraN8pvXLBej3K_arnSJ-jcml-Ny2yw8LA0rf38L2NP3kVR-9TN-wKuu-BdmIR_YqC7Vl0TjfVy58Q8m3cUDCj77Kgk0-KAZ9eiQ2i_1UHWzuCnHjBS6KOQ5We1KftPcI2YW-_ew",
  "payload": ""
}
2024-01-17 06:02:01,549:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/305050750456 HTTP/1.1" 200 797
2024-01-17 06:02:01,550:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 17 Jan 2024 06:02:00 GMT
Content-Type: application/json
Content-Length: 797
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4dyidfNPtXhF0Typza24tdlCwHBSJhQSFNag2RakOGTZE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "tairot.online"
  },
  "status": "pending",
  "expires": "2024-01-24T06:02:00Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/bmDqMg",
      "token": "bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/IqOynQ",
      "token": "bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/954fLw",
      "token": "bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw"
    }
  ]
}
2024-01-17 06:02:01,551:DEBUG:acme.client:Storing nonce: wFJtXv4dyidfNPtXhF0Typza24tdlCwHBSJhQSFNag2RakOGTZE
2024-01-17 06:02:01,552:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-01-17 06:02:01,552:INFO:certbot._internal.auth_handler:http-01 challenge for tairot.online
2024-01-17 06:02:01,553:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-01-17 06:02:01,553:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-01-17 06:02:01,560:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw
2024-01-17 06:02:01,563:DEBUG:acme.client:JWS payload:
b'{}'
2024-01-17 06:02:01,564:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/bmDqMg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZHlpZGZOUHRYaEYwVHlwemEyNHRkbEN3SEJTSmhRU0ZOYWcyUmFrT0dUWkUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzMwNTA1MDc1MDQ1Ni9ibURxTWcifQ",
  "signature": "S-U59ZE7oQWaUEFBW-XhqJzKNX1clJl4QWq5pCtrH9jc8_o5QWqXJniuOwhLfByEjbkGOKTChg4diwRycBbQQf9jeuKF4LIHzVTRsfxZ3eOeUVxo_N6tGesoI7kvjTG6Ab1M9OE4pUF7ufVcPjBdJ6h2kTBWC1eUCaJZDI4dvF0xUBMgUL6UgxJkByCbTcNzcjB8-QFBEOu5yM9cKiIQQL7uUs8WUhQU1wzlUy-ZaRW-5xxi9Jc1HvAqKG-CNbtD9-mXRtBZ67m-rPgJfQ6GXIZiSuIr3jqIhaSuIAKrwfrCqzc9j2WfmZXuKIm1hfzdmE71lZMUMFAKv9n2hQXbdg",
  "payload": "e30"
}
2024-01-17 06:02:01,749:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/305050750456/bmDqMg HTTP/1.1" 200 187
2024-01-17 06:02:01,750:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 17 Jan 2024 06:02:01 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/305050750456>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/bmDqMg
Replay-Nonce: wFJtXv4df1fQMCAaAjH7b08FedqGLnAP9WNsnxX9jVS3Xo825Qc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/bmDqMg",
  "token": "bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw"
}
2024-01-17 06:02:01,751:DEBUG:acme.client:Storing nonce: wFJtXv4df1fQMCAaAjH7b08FedqGLnAP9WNsnxX9jVS3Xo825Qc
2024-01-17 06:02:01,751:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-01-17 06:02:02,753:DEBUG:acme.client:JWS payload:
b''
2024-01-17 06:02:02,754:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/305050750456:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZGYxZlFNQ0FhQWpIN2IwOEZlZHFHTG5BUDlXTnNueFg5alZTM1hvODI1UWMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNTA1MDc1MDQ1NiJ9",
  "signature": "YMt4jPZKn8c7dRh8HhVXPAOW2hWgV-7yYMyXiHcrhXIbnJ3jmf5CmhSs3lQGARbgLeU9TlM5ZB1z-JLJNZ55IdI3_nwlwXAUD-20PSg1uVV4eDGjwv0XtjcBVBRsUuw1FakVxDBeQhHVGu_T3w8F3fBekC6pNl3ixtlTqCOd3rSL7xvV7M3UuuSX1YNqJGtC6x2w72CP-dNNF0AWke2GbVnP6J7ZYgzWgtzdDn_NJsmBGz4KPIYjIeQz6F9QQL4sqh3I3O1LOtGPKpB5Ct0Z5qZyDZ1x6v6T9lAnhNkxYtbXdRl7NU_N6d1o4JhQMOPuhcFtgrAbd7x25Y9KHFJvMg",
  "payload": ""
}
2024-01-17 06:02:02,946:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/305050750456 HTTP/1.1" 200 1023
2024-01-17 06:02:02,947:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 17 Jan 2024 06:02:02 GMT
Content-Type: application/json
Content-Length: 1023
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: cBLV7b5iC6JAFwRwRmI3EZdZREVwxhO3ipsRSR9LO7wGmkCiow0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "tairot.online"
  },
  "status": "invalid",
  "expires": "2024-01-24T06:02:00Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "43.202.208.226: Fetching http://tairot.online/.well-known/acme-challenge/bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/305050750456/bmDqMg",
      "token": "bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw",
      "validationRecord": [
        {
          "url": "http://tairot.online/.well-known/acme-challenge/bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw",
          "hostname": "tairot.online",
          "port": "80",
          "addressesResolved": [
            "43.202.208.226"
          ],
          "addressUsed": "43.202.208.226"
        }
      ],
      "validated": "2024-01-17T06:02:01Z"
    }
  ]
}
2024-01-17 06:02:02,948:DEBUG:acme.client:Storing nonce: cBLV7b5iC6JAFwRwRmI3EZdZREVwxhO3ipsRSR9LO7wGmkCiow0
2024-01-17 06:02:02,949:INFO:certbot._internal.auth_handler:Challenge failed for domain tairot.online
2024-01-17 06:02:02,950:INFO:certbot._internal.auth_handler:http-01 challenge for tairot.online
2024-01-17 06:02:02,951:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: tairot.online
  Type:   connection
  Detail: 43.202.208.226: Fetching http://tairot.online/.well-known/acme-challenge/bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-01-17 06:02:02,952:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-01-17 06:02:02,953:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-01-17 06:02:02,953:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-01-17 06:02:02,954:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/bX9orzgf5BOdhBXWWfpiNX3DEQ0dLcdpX1FKjL-E7gw
2024-01-17 06:02:02,959:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-01-17 06:02:02,959:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-01-17 06:02:02,960:ERROR:certbot._internal.log:Some challenges have failed.
