2024-01-16 12:30:31,525:DEBUG:certbot._internal.main:certbot version: 2.8.0
2024-01-16 12:30:31,526:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-01-16 12:30:31,526:DEBUG:certbot._internal.main:Arguments: ['-v', '--webroot', '--webroot-path=/var/www/certbot', '--email', 'tjfgkssk9472@gmail.com', '--agree-tos', '--no-eff-email', '-d', '1tsme.site']
2024-01-16 12:30:31,526:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-01-16 12:30:31,607:DEBUG:certbot._internal.log:Root logging level set at 20
2024-01-16 12:30:31,608:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-01-16 12:30:31,609:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0xffff926e4a30>
Prep: True
2024-01-16 12:30:31,609:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0xffff926e4a30> and installer None
2024-01-16 12:30:31,609:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-01-16 12:30:31,659:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1519022676', new_authzr_uri=None, terms_of_service=None), 053f50e92556dc2ae6fb1958ad04b4cb, Meta(creation_dt=datetime.datetime(2024, 1, 16, 8, 39, 49, tzinfo=<UTC>), creation_host='1b0b13fa81e7', register_to_eff=None))>
2024-01-16 12:30:31,660:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-01-16 12:30:31,662:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-01-16 12:30:32,273:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-01-16 12:30:32,275:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 12:30:32 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "2PEq86nqenU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-01-16 12:30:32,279:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for 1tsme.site
2024-01-16 12:30:32,286:DEBUG:acme.client:Requesting fresh nonce
2024-01-16 12:30:32,287:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-01-16 12:30:32,498:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-01-16 12:30:32,499:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 12:30:32 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4dW__FAuO5LitV9cRn4S2kiJSNIq0vDROkRpa0gfz283M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-01-16 12:30:32,499:DEBUG:acme.client:Storing nonce: wFJtXv4dW__FAuO5LitV9cRn4S2kiJSNIq0vDROkRpa0gfz283M
2024-01-16 12:30:32,500:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "1tsme.site"\n    }\n  ]\n}'
2024-01-16 12:30:32,502:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZFdfX0ZBdU81TGl0VjljUm40UzJraUpTTklxMHZEUk9rUnBhMGdmejI4M00iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "DNNXYpQfVpjr7yiYcew1Z5aNL7-DYpE7-_-nirBFrkttYs1wSAVO8Ce7YPN0M0xtE8YxFMCe9CauWhFqiB8e_QTKQLtwWBkxihSrkjZmR9WOOliz3ZVujiAeebirlOQQZYKsIM4eMMSKKuyuTE0Lzyvb65voHa3Ni33bR5cYdKJHhtiFMaXY0MNy7qdmStooTGcIomagoDyKRcgh41nc3xDucXNINWdBxBaSrb_8s2dGYrkIb_zFZ8t3uGeP8ci6NyoEGMRyTMSovRjxTqDGD_Zuw8fFYpOvycTYD6_tFqI2fqiGlahnM8lMg6nbaxDo8QKN890pfNRGbPgSOLhMHQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIjF0c21lLnNpdGUiCiAgICB9CiAgXQp9"
}
2024-01-16 12:30:32,882:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 336
2024-01-16 12:30:32,887:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Tue, 16 Jan 2024 12:30:32 GMT
Content-Type: application/json
Content-Length: 336
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1519022676/237108685446
Replay-Nonce: wFJtXv4dMmKYeDqvZSR4XlIIHYDtmeuJ0mchyadNPyDn4gOyBmM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-01-23T12:30:32Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "1tsme.site"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/304794561256"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1519022676/237108685446"
}
2024-01-16 12:30:32,888:DEBUG:acme.client:Storing nonce: wFJtXv4dMmKYeDqvZSR4XlIIHYDtmeuJ0mchyadNPyDn4gOyBmM
2024-01-16 12:30:32,889:DEBUG:acme.client:JWS payload:
b''
2024-01-16 12:30:32,894:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/304794561256:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZE1tS1llRHF2WlNSNFhsSUlIWUR0bWV1SjBtY2h5YWROUHlEbjRnT3lCbU0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNDc5NDU2MTI1NiJ9",
  "signature": "ZezW6-sV-3J5tySkZkhEZ5NljEVQ3ry7uB09pcyMd-sgvg27kYpgqODNDU90U3_D--E51WGz_OGA1qZwI0LR2kQNT_rsZ5hfAsYVXQ0uQEp4a8v7kNu5AcIi41K0tq5WZzkdt89MpzfDCU3rErXXmzNZS_-UmDis1dIQe_2BcANNA3K0sK78OmYLbEJm2o0DEygWzhBm_LT2DvWviiTE-WEhBE6DBQ-bd-HbW16069B3lyRj3sM2k5ZIKdBfNM3FEHsKSEk5lrAhmgoW_TzsmxggCMg2uvbPM5kmPbkGfEz7QeJYLNwAzWMmQid7rUewT0DWTiVokFucJCWJsqmFjw",
  "payload": ""
}
2024-01-16 12:30:33,119:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/304794561256 HTTP/1.1" 200 794
2024-01-16 12:30:33,130:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 12:30:33 GMT
Content-Type: application/json
Content-Length: 794
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: cBLV7b5itqCfMLOEk3MvKhwROIBtvTZcAWW6fgYGPucUDEOYDWo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "1tsme.site"
  },
  "status": "pending",
  "expires": "2024-01-23T12:30:32Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/NN0mIw",
      "token": "eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/Qfv-5g",
      "token": "eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/VQfG6g",
      "token": "eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0"
    }
  ]
}
2024-01-16 12:30:33,130:DEBUG:acme.client:Storing nonce: cBLV7b5itqCfMLOEk3MvKhwROIBtvTZcAWW6fgYGPucUDEOYDWo
2024-01-16 12:30:33,131:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-01-16 12:30:33,131:INFO:certbot._internal.auth_handler:http-01 challenge for 1tsme.site
2024-01-16 12:30:33,132:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-01-16 12:30:33,132:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-01-16 12:30:33,134:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0
2024-01-16 12:30:33,136:DEBUG:acme.client:JWS payload:
b'{}'
2024-01-16 12:30:33,145:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/NN0mIw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJjQkxWN2I1aXRxQ2ZNTE9FazNNdktod1JPSUJ0dlRaY0FXVzZmZ1lHUHVjVURFT1lEV28iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzMwNDc5NDU2MTI1Ni9OTjBtSXcifQ",
  "signature": "lia0B4p3psEgG3HNQQBxppaNIe5Es3scfUu-M699_ESHOrkuRcOaYaWR7a0keb8CrfVGnc8TLJEEpBeQ55-lc8rwzpSqLwd66IPstraXuM1TiKP4aNlo5suXymWxi7LRHMoe4vhA5Pm50iTBHbqQHP9EWk0aV7suFXEfSjdBiH2D-gESW3_WBXQrvOh8f5bYT7nucN2Uyu-vuRQnSaw75nQbAHuY4-jqmVOgrxkRSfPUqzgoGyCBD24wNzJvj6fnYi7Yy3tCZ60rRM6w3BJsOSeGl6OrgYK0RrB7sdruY2YVEIpVbr2oYlsysiNk77vnfIubiv3s_DOBcPBXXszpxQ",
  "payload": "e30"
}
2024-01-16 12:30:33,361:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/304794561256/NN0mIw HTTP/1.1" 200 187
2024-01-16 12:30:33,363:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 12:30:33 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/304794561256>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/NN0mIw
Replay-Nonce: wFJtXv4dg0xQByUrrb1Gq-HFWUII_LFyjULhBFByi14m6wK5GPA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/NN0mIw",
  "token": "eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0"
}
2024-01-16 12:30:33,367:DEBUG:acme.client:Storing nonce: wFJtXv4dg0xQByUrrb1Gq-HFWUII_LFyjULhBFByi14m6wK5GPA
2024-01-16 12:30:33,370:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-01-16 12:30:34,373:DEBUG:acme.client:JWS payload:
b''
2024-01-16 12:30:34,380:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/304794561256:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZGcweFFCeVVycmIxR3EtSEZXVUlJX0xGeWpVTGhCRkJ5aTE0bTZ3SzVHUEEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNDc5NDU2MTI1NiJ9",
  "signature": "izpBnRYTkKN8-8NU65-xN2l8g2gQQsI15UmBy4k6nP5ovA1CANtvUM6phYmdVwhsMSMbAzAeKn-_zZM5y0kIu3fetPOwCOv-y7YoE8a4XGpAWue7Zzd6hL60igHpqmean4kLXb-UK1vWVZ8_V1eRWe-eU87iqiIZNsy1t661YIi5I20e7euafnpaIAwJ6p_g9KcgcnT6EKhMuMEg_rIbPp-bpK0tPKn6AedmL9tQrRG6Fb1pyzEHJNt12pmGaigPFzKTygtdlJIwPiQwofciIV5bKLXkRhNZQQMDaKY1QXIpAp35cuTgQwHB46eSNclrw5XMQqBJJ6o5yxPzYIyKjQ",
  "payload": ""
}
2024-01-16 12:30:34,595:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/304794561256 HTTP/1.1" 200 729
2024-01-16 12:30:34,598:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 12:30:34 GMT
Content-Type: application/json
Content-Length: 729
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4defbs0n_CO2A35oF_NEh2X0ecB5nq4mCctSWPoTu_qMU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "1tsme.site"
  },
  "status": "invalid",
  "expires": "2024-01-23T12:30:32Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: SERVFAIL looking up A for 1tsme.site - the domain's nameservers may be malfunctioning; DNS problem: SERVFAIL looking up AAAA for 1tsme.site - the domain's nameservers may be malfunctioning",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304794561256/NN0mIw",
      "token": "eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0",
      "validated": "2024-01-16T12:30:33Z"
    }
  ]
}
2024-01-16 12:30:34,600:DEBUG:acme.client:Storing nonce: wFJtXv4defbs0n_CO2A35oF_NEh2X0ecB5nq4mCctSWPoTu_qMU
2024-01-16 12:30:34,602:INFO:certbot._internal.auth_handler:Challenge failed for domain 1tsme.site
2024-01-16 12:30:34,605:INFO:certbot._internal.auth_handler:http-01 challenge for 1tsme.site
2024-01-16 12:30:34,608:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: 1tsme.site
  Type:   dns
  Detail: DNS problem: SERVFAIL looking up A for 1tsme.site - the domain's nameservers may be malfunctioning; DNS problem: SERVFAIL looking up AAAA for 1tsme.site - the domain's nameservers may be malfunctioning

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-01-16 12:30:34,610:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-01-16 12:30:34,611:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-01-16 12:30:34,611:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-01-16 12:30:34,612:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/eOhmPB-9smd3eZT5Ym916QK2S8-OoQq3UiHpMUuV-W0
2024-01-16 12:30:34,615:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-01-16 12:30:34,616:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-01-16 12:30:34,618:ERROR:certbot._internal.log:Some challenges have failed.
